import NavBar from "@/components/navigation-bar";
import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import FooterSection from "@/components/footer-section";

const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Frontend Mentor - Guru Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <NavBar />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
